In [4]:
%reload_ext autoreload
%autoreload 2

from scraiping import make_url, Scraiping
from helpers import Relative, Choise
from methods import Winning

In [11]:
info = ['2020', '65', '0620', '01'] #[年, 会場,　月日,　レース番号] (会場 : 門別=30, 水沢=36, 船橋=43, 笠松=47, 園田=50, 高知=54, 佐賀=55, 帯広=65, et.al)

In [12]:
tansyo_url, umatan_url = make_url(info)

In [13]:
sc_df = Scraiping(tansyo_url, umatan_url).get()
sc_df

,名前,単勝,1,2,3,4,5,6,7,8,9,10
馬番,,,,,,,,,,,,
1,キタノエンジュ,16.0,NaN,125.0,555.9,208.4,45.4,45.4,92.6,416.9,106.4,113.7
2,ロングブラック,12.4,128.2,NaN,500.3,200.1,45.4,32.4,96.2,454.8,54.3,192.4
3,ナカゼンダー,59.3,454.8,333.5,NaN,312.7,78.1,128.2,312.7,714.7,151.6,416.9
4,オオネガイクィーン,20.3,250.1,238.2,714.7,NaN,46.3,48.5,83.3,625.4,104.2,138.9
5,ハクホウエイ,4.6,78.1,68.5,217.5,64.1,NaN,16.0,35.9,294.3,18.3,50.0
6,サカノメイショウ,2.9,70.4,44.6,333.5,43.8,15.0,NaN,25.0,263.3,20.6,42.7
7,エフノバイブス,7.2,111.1,119.1,333.5,70.4,24.1,21.1,NaN,333.5,32.2,45.0
8,ツルイセイウン,55.5,500.3,416.9,833.8,454.8,142.9,113.7,200.1,NaN,131.6,277.9
9,キタノヒカリ,4.7,178.6,86.2,312.7,100.0,18.3,16.7,37.0,250.1,NaN,37.3
10,リュウコ,8.0,142.9,227.4,555.9,135.2,25.9,45.4,53.2,312.7,32.7,NaN

In [14]:
re_df = Relative(sc_df).sum_odds()
re_df

      単勝       馬単合成          差
馬番
1   16.0  15.479198  -0.520802
2   12.4  12.656602   0.256602
3   59.3  45.479884 -13.820116
4   20.3  11.733597  -8.566403
5    4.6   3.485919  -1.114081
6    2.9   3.547299   0.647299
7    7.2   6.448552  -0.751448
8   55.5  40.021952 -15.478048
9    4.7   4.620385  -0.079615
10   8.0   8.358398   0.358398

In [15]:
Choise(re_df).combine()

['2', '6', '10', ('2', '6'), ('2', '10'), ('6', '10')]

In [20]:
Wi = Winning(sc_df['単勝'], sc_df['2'], sc_df['6'])
model = Wi.model_0()
result = Wi.result(model)
print(result[1])
result[0]

Not solved

        オッズ        確率  ベット(枚)   払い戻し金(円)      差額(円)
馬番
1      16.0  0.050000  1581.0  2529600.0     -300.0
3      59.3  0.013491    35.0   207550.0 -2322350.0
4      20.3  0.039409  1246.0  2529380.0     -520.0
5       4.6  0.173913  5497.0  2528620.0    -1280.0
7       7.2  0.111111  3512.0  2528640.0    -1260.0
8      55.5  0.014414    44.0   244200.0 -2285700.0
9       4.7  0.170213  5380.0  2528600.0    -1300.0
10      8.0  0.100000  3161.0  2528800.0    -1100.0
2-1   125.0  0.003448    22.0   275000.0 -2254900.0
2-3   333.5  0.000930     9.0   300150.0 -2229750.0
2-4   238.2  0.002718    12.0   285840.0 -2244060.0
2-5    68.5  0.011994    40.0   274000.0 -2255900.0
2-6    44.6  0.019025    62.0   276520.0 -2253380.0
2-7   119.1  0.007663    24.0   285840.0 -2244060.0
2-8   416.9  0.000994     7.0   291830.0 -2238070.0
2-9    86.2  0.011739    33.0   284460.0 -2245440.0
2-10  227.4  0.006897    13.0   295620.0 -2234280.0
6-1    45.4  0.019048    62.0   281480.0 -2248420.0
6-2    32.4  0.024578    88.0   285120.0 -2244780.0
6-3   128.2  0.005139    23.0   294860.0 -2235040.0
6-4    48.5  0.015013    59.0   286150.0 -2243750.0
6-5    16.0  0.066253  1581.0  2529600.0     -300.0
6-7    21.1  0.042328  1199.0  2529890.0      -10.0
6-8   113.7  0.005491    27.0   306990.0 -2222910.0
6-9    16.7  0.064843  1514.0  2528380.0    -1520.0
6-10   45.4  0.038095    68.0   308720.0 -2221180.0